#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Self Analysis
title: Self Analysis

# Short description
description: Keep yourself in check

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
# TODO
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# TODO
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/self-analysis-ios"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
# https://github.com/barryclark/jekyll-now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
# https://pages.github.com/versions/
kramdown:
  auto_ids: true # automatic generation of header IDs
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
- jemoji
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- .idea
